spring:
  datasource:
    url: jdbc:h2:file:${H2_FILE_BASE_PATH:D:/deploy/research-management-platform-v2/backend/data/research-management-platform};MODE=MySQL;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: ${H2_USERNAME:sa}
    password: ${H2_PASSWORD:}
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: ${APP_JPA_DDL_AUTO:update}
    defer-datasource-initialization: false
